name: Deploy CloudFormation and Microservices

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339495302685:role/github-ecr-role
          aws-region: ap-south-1

      - name: Deploy CloudFormation Stack
        run: |
          set -x
          echo "========= Deploying CloudFormation Stack ========="
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name microservices-stack --region ap-south-1 --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DELETE")
          if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
            echo "Stack in ROLLBACK_COMPLETE. Deleting stack..."
            aws cloudformation delete-stack --stack-name microservices-stack --region ap-south-1
            aws cloudformation wait stack-delete-complete --stack-name microservices-stack --region ap-south-1
          fi
          aws cloudformation deploy \
            --stack-name microservices-stack \
            --template-file cloudformation.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ap-south-1 \
            --no-fail-on-empty-changeset \
            --parameter-overrides KeyName=cloudformationdeploy AmiId=ami-018046b953a698135 || (
            echo "Deployment failed. Showing stack CREATE_FAILED reasons:" ;
            aws cloudformation describe-stack-events --stack-name microservices-stack --region ap-south-1 --query "StackEvents[?ResourceStatus=='CREATE_FAILED'].{Resource:LogicalResourceId,Reason:ResourceStatusReason}" --output table ;
            exit 1 )
          echo "========= CloudFormation Deployment Complete ======"
          aws cloudformation describe-stacks --stack-name microservices-stack --region ap-south-1 \
            --query "Stacks[0].Outputs" --output table

      - name: Print CloudFormation Stack Events (Always)
        if: always()
        run: |
          echo "========= Printing last 20 CloudFormation stack events ========="
          aws cloudformation describe-stack-events \
            --stack-name microservices-stack \
            --region ap-south-1 \
            --query "StackEvents[0:20].[Timestamp,LogicalResourceId,ResourceType,ResourceStatus,ResourceStatusReason]" \
            --output table || echo "No events found (stack may not exist yet)."      

      - name: SSH and Deploy Containers with Secrets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -ex
            echo "========= Changing to deployment-infra directory ========="
            cd /home/ec2-user/deployment-infra

            echo "========= Writing .env file ========="
            cat > .env <<EOF
            MYSQL_DB=${{ secrets.MYSQL_DB }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            # Add more secrets as needed
            EOF
            echo "[INFO] .env file created with secrets"

            echo "========= Starting deploy.sh script ========="
            cd scripts
            chmod +x deploy.sh
            ./deploy.sh
            echo "[INFO] deploy.sh script execution completed"
